### ISSUE TITLE
ImportError: No module named 'spark.matrix'

### ISSUE THREAD

**Issue by cicimagicai** [w34ma/spark-cnn#1]
Hi, 

I try to run python3 naive_train.py 100 100, but it fails and reported the following bug:

Traceback (most recent call last):
  File "naive_train.py", line 3, in <module>
    from spark.cnn import CNN
  File "/home/jiaxin/spark-cnn/spark/cnn.py", line 3, in <module>
    from spark.conv import ConvolutionLayer
  File "/home/jiaxin/spark-cnn/spark/conv.py", line 7, in <module>
    from spark.matrix import *
ImportError: No module named 'spark.matrix'

I already run python3 setup.py build and so on for the source code package. Could you please tell me how to fix this bug? 
Thanks a lot!

**Comment by w34ma** [comment]
You need to first build the Cython extension in the spark directory
